### ISSUE TITLE
Set up GitHub actions

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#1]
- [x] Set up unit tests for different python versions.
- [x] Set up unit tests for different operating systems.
- [x] Set up unit tests coverage test.
- [x] Set up sphinx documentation test.
- [x] Set up copyright tests.
- [x] Set up flake8 tests.

**Comment by DavAug** [comment]
For some inspiration:
https://github.com/pints-team/pints/tree/master/.github/workflows

They use run-tests.py to execute the tests.
https://github.com/pints-team/pints/blob/master/run-tests.py

**Comment by I-Bouros** [comment]
Started setting up the dummy classes and respective unit tests as in pull request #10. The setup of the yml files for the referenced workflows to continue shortly.

**Comment by rcw5890** [comment]
As of #10, this is in progress.

**Comment by ao20** [comment]
Great debugging @rcw5890
