### ISSUE TITLE
Create Visualisation class

### ISSUE THREAD

**Issue by I-Bouros** [SABS-R3-Epidemiology/branchpro#11]
Create Visualisation class.

- [ ] Create `visualisation.py` file in branchpro directory.
- [ ] Within `visualisation.py`, create a class called `Visualisation` which takes an instance of `SimulationController`, see #9.
- [ ]  Implement a method called `histogram` which takes a simulated sample of the model and plots it as a histogram

**Comment by rcw5890** [comment]
Superseded by later work
