### ISSUE TITLE
Add upload file templates

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#130]
Add to the apps a template, illustration, or detailed description of the expected file formats.

**Comment by I-Bouros** [comment]
Also, maybe we can improve the way the apps look like using some of the bootstrap components in here?

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/

**Comment by rcw5890** [comment]
> Also, maybe we can improve the way the apps look like using some of the bootstrap components in here?
> 
> https://dash-bootstrap-components.opensource.faculty.ai/docs/components/

That's a very good find, and I agree. The danger alert would be nice for incorrect file uploads.
Popover and Modal could also be useful.
