### ISSUE TITLE
Start studying Australia data

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#133]
Look at the inference results, and observe the effects of epsilon.

- [x] New South Wales
- [x] Victoria
- [x] Queensland
- [x] South Australia
- [x] Western Australia
- [x] Tasmania
- [x] Capital Territory

**Comment by rcw5890** [comment]
Try values of epsilon = -1 to 1, in steps of 0.2.

Consider time points March 10, March 20, March 30. At each time point, plot the posterior at each epsilon in a grouped box plot.

https://plotly.com/python/box-plots/

**Comment by FarmHJ** [comment]
Completed #145
