### ISSUE TITLE
Setup docstring test github action

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#17]
Partially addresses #1 .

Add the docstring header 

```
#
# This file is part of branchpro (https://github.com/SABS-R3-Epidemiology/branchpro/)
# which is released under the BSD 3-clause license. See accompanying LICENSE.md
# for copyright notice and full license details.
#
```

to all python files in the repository, and then create a GitHub action that checks that the license header is present in all python files. Hint: this is easiest by adding a `run-tests.py --copyright` functionality similar to pints: 
worklfow: https://github.com/pints-team/pints/blob/master/.github/workflows/copyright-test.yml
run-tests.py: https://github.com/pints-team/pints/blob/master/run-tests.py

**Comment by rcw5890** [comment]
Should be done now that #24 is merged.
