### ISSUE TITLE
Make a repository for results

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#186]
- [x] Make a new repository under SABS-R3-Epidemiology with a name such as "Transmission-heterogeneity-results," or whatever you think is best (we may just change the name later)
- [x] Add a data directory, and move the covid, mers, and serial interval data from here to there
- [x] Add a directory for notebooks, and place in it the notebooks from branchpro/branchpro/results 
  - Wait for #180, #184, #185 to get merged
- [x] Edit the filenames of the notebooks to include the figure number from the paper and a description
- [x] Add a figures directory. Make sure the notebooks save their figures to this directory, with consistent filenames matching the paper
- [x] Add a copy of Figure 1 (schematic) to this directory as well
- [x] Write a readme describing the repository, and mention this repository (branchpro) as the source of the code
- [x] Write a makefile which executes all notebooks and saves the figures

**Comment by rcw5890** [comment]
Ben has some possibly relevant notes here:
https://github.com/ben18785/reproducible-data-analysis/blob/main/presentations/reproducible_analysis.md

**Comment by FarmHJ** [comment]
I think this can be closed now?

**Comment by rcw5890** [comment]
https://github.com/SABS-R3-Epidemiology/transmission-heterogeneity-results
