### ISSUE TITLE
Finalize app text

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#197]
- [x] Add a paragraph to the top text, saying that users can upload their own data and that this data can optionally include imported cases. 
- [x] Mention epsilon as the relative transmission risk between imported cases and local cases.
- [x] Add a link to go back to https://sabs-r3-epidemiology.github.io/branchpro/

**Comment by ao20** [comment]
Ready.

**Comment by rcw5890** [comment]
Looks good, thanks
