### ISSUE TITLE
Solve task 1 form exercise sheet

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#22]
Create a Jupyter notebook that uses the
- [ ] BranchProModel class

to solve task 1 from the exercise sheet.

See sheet:
https://benlambertdotcom.files.wordpress.com/2020/10/branching-process-models-handout.pdf

Visualise the simulation using plotly's histograms.
https://plotly.com/python/histograms/

**Comment by rcw5890** [comment]
Now that the BranchProModel class is available, this notebook is under construction
