### ISSUE TITLE
Create add_r_step

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#23]
Create a method called `add_r_step` that 
- [ ] takes an r value a start and optionally an end time point
- [ ] updates the current r profile to assume the input r value between the start and end time
- [ ] if no end time is provided, the input r value is assumed until the end of the simulation.

**Comment by DavAug** [comment]
After some thought I'd like to have a discussion about the best solution for this again.

The question is how do we best defines a time-dependent r profile, in light of the fact that for the inference we will need an array of R values for each step in a specified time unit.

My most recent thoughts on this is that an `add_r_step` function may not be the best way to address this issue. We may instead only focus on a method called `set__n_reproduction_profile` or something like that takes a 2 dim array of R and time values, and constructs a profile from that.

For the inference we can then just overwrite and slightly modify this method to take a 1d array of lenght n_times. 

Points to address:
- [ ] Ease of use for simulation
- [ ] Interface with pints

**Comment by I-Bouros** [comment]
> After some thought I'd like to have a discussion about the best solution for this again.
> 
> The question is how do we best defines a time-dependent r profile, in light of the fact that for the inference we will need an array of R values for each step in a specified time unit.
> 
> My most recent thoughts on this is that an `add_r_step` function may not be the best way to address this issue. We may instead only focus on a method called `set__n_reproduction_profile` or something like that takes a 2 dim array of R and time values, and constructs a profile from that.
> 
> For the inference we can then just overwrite and slightly modify this method to take a 1d array of lenght n_times.
> 
> Points to address:
> 
> * [ ]  Ease of use for simulation
> * [ ]  Interface with pints

On this note, this is exactly what the add_r_step method I had going on is actually doing, i.e. creating and updating two matrix like profiles, one for r and one for t, and the reproduction_num method only collapses them both to create a long matrix (extended profile if you will) to feed in the _normalising_mean method.

I have no qualms about renaming the add_r_steps method, or about collapsing the two separate profiles in a two-row matrix for economy of memory.

**Comment by DavAug** [comment]
@I-Bouros and I resolved this issue by implementing a method called `set_r_profile`. See documentation for details of how this method works.

**Comment by I-Bouros** [comment]
Finalised class and tests successfully.
