### ISSUE TITLE
Plan software structure

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#3]
Before we do anything, let's have a look at the goal of the project:
1. We have a branching process model which is defined by a number of parameters
2. We are supposed to solve this model within a given time duration for a given set of model parameters
3. We are supposed to illustrate the results in terms of a histogram plot, where the x axis is the time in days and the y axis is the number of infections on that day.

In this issue we will collect ideas of how we might tackle this task. In particular, we'll address 
- [ ] How do we want to demonstrate that we solved the task?
- [ ] How do we want to define the model? (A function or a class? If a class which methods would be useful?) 
- [ ] How do we want to simulate the model, such that the simulation can be easily extended to other models? Hint: Do you think it's a good idea that the "Simulator" has any specific information about the model?
- [ ] How do we want to illustrate the simulation? (Do you know any cool packages?)

**Comment by ao20** [comment]
Write introduction to the task in a Jupyter notebook, stating the task to be solved (intro/exposition) and then presenting our results.

**Comment by DavAug** [comment]
Possibly a plotly dash app, e.g. https://dash.plotly.com/basic-callbacks

**Comment by rcw5890** [comment]
Here's the class that Pints uses for models:
https://pints.readthedocs.io/en/stable/core_classes_and_methods.html#pints.ForwardModel

**Comment by rcw5890** [comment]
Regarding forward models in the stochastic case:

This is an old Pints pull request for a stochastic model. As far as I can tell, the idea was that each call of ForwardModel.simulate(...) gives one sample of a solution. Call it multiple times to see the distribution of possible solutions.  

https://github.com/pints-team/pints/pull/1025

**Comment by DavAug** [comment]
> Regarding forward models in the stochastic case:
> 
> 
> 
> This is an old Pints pull request for a stochastic model. As far as I can tell, the idea was that each call of ForwardModel.simulate(...) gives one sample of a solution. Call it multiple times to see the distribution of possible solutions.  
> 
> 
> 
> https://github.com/pints-team/pints/pull/1025

That is definitely an option, but I suspect that it will take quite some time to converge. Alternatively, if the model can be expressed as probability distribution, we could just use this to define our likelihood. And correct me if I'm wrong, but I do think that we can do that in our case.

**Comment by rcw5890** [comment]
> Alternatively, if the model can be expressed as probability distribution, we could just use this to define our likelihood.

Yes, this sounds like a good idea.

**Comment by I-Bouros** [comment]
A rough idea about the structural architecture and some of the features and methods we can include in each class:

1. Model Class 
* features to be included: the serial interval w_s, as they are the only stationary data we have about the model.
* create method: inference of Rt numbers - uses a vector of simulated data and the numbers w_s that define
                                                                                                   the model

2. Simulation Class 
* I_t are the quantities we would like to track;
* create method: draw vector of simulated data; at each draw simulate using Model class [inherited - (not 
                                                                                                                   the right word ?) features] - MCMC sampling algorithm? Or a Sequential Monte Carlo maybe? Or Metropolis - Hastings?

/\/ create a different method of sampling for each model; with raiseErrors if the type of model used does not match the method of simulation we chose for it

3. Visualisation Class:
* create method: for plotting the histogram using the vector of simulated # cases per day;
                                                                   maybe also plot the line of expected # of cases per day / expectation of Poss dist 
                                                                   used

Type of dependencies of classes that I envisage would go on:

<img width="447" alt="Screenshot 2020-10-26 at 18 27 58" src="https://user-images.githubusercontent.com/72917474/97213027-0c703180-17b9-11eb-9f17-970a95e4dac6.png">

**Comment by DavAug** [comment]
Planning phase closed for now.
