### ISSUE TITLE
Write initial issues for the simulation dashboard

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#4]
Convert ideas collected in #3 into detailed issues.

**Comment by rcw5890** [comment]
I'll stick some thoughts on appropriate issues here, so we can discuss/edit them before actually opening issues.

**Comment by rcw5890** [comment]
Issue: Write a class for the branching process model (it can be empty for now), and write a class docstring explaining the model. Include literature references and mathematical equations as necessary. Check pints for examples, such as https://github.com/pints-team/pints/blob/master/pints/toy/_logistic_model.py

**Comment by rcw5890** [comment]
Issue: Add a method to the branching process model class that simulates one trajectory of the branching process model, conditional on a fixed set of R_t, w_s and number of days. It should return a numpy array giving the integer number of cases on each day, on one run of the stochastic process.

(See Task 1 in the handout.)

**Comment by rcw5890** [comment]
Issue: Make a presentable visual aid to complete Task 1 on the handout.

(Not sure if we should jump right into plotly interactive for this, or do a simple notebook first and then upgrade it later in the week.)

**Comment by I-Bouros** [comment]
> Issue: Write a class for the branching process model (it can be empty for now), and write a class docstring explaining the model. Include literature references and mathematical equations as necessary. Check pints for examples, such as https://github.com/pints-team/pints/blob/master/pints/toy/_logistic_model.py

I am creating these dummy classes and test cases to be able to start implementing the workflows in #1. Is that what you refer to in this issue draft?

**Comment by DavAug** [comment]
> > Issue: Write a class for the branching process model (it can be empty for now), and write a class docstring explaining the model. Include literature references and mathematical equations as necessary. Check pints for examples, such as https://github.com/pints-team/pints/blob/master/pints/toy/_logistic_model.py
> 
> I am creating these dummy classes and test cases to be able to start implementing the workflows in #1. Is that what you refer to in this issue draft?

Hi @I-Bouros 
I think having a file `dummy.py` which contains a function
```
def dummy_function():
    return 42
```

And an associated test file `test_dummy.py` 
```
import unittest

from branchpro.dummy import dummy_function


class TestDummyFunction(unittest.TestCase):
    def test_output(self):
        self.assertEqual(dummy_function(), 42)
```

Should suffice.
```

**Comment by DavAug** [comment]
So no need to use anything more complicated.

**Comment by I-Bouros** [comment]
@DavAug What if I already started doing for three classes (model, simulation, visualisation), the type of files that you said. Is that okay?

**Comment by DavAug** [comment]
> @DavAug What if I already started doing for three classes (model, simulation, visualisation), the type of files that you said. Is that okay?

That's great and very useful for what we want to do for the rest of the week! What I would suggest is that you please keep those classes in a separate branch for now, and ones we've created issues for those classes in an hour or two, create branches that reference those issues.

**Comment by DavAug** [comment]
For the GitHub actions and dummy test, I'd suggest to use something simpler.

**Comment by I-Bouros** [comment]
> > @DavAug What if I already started doing for three classes (model, simulation, visualisation), the type of files that you said. Is that okay?
> 
> That's great and very useful for what we want to do for the rest of the week! What I would suggest is that you please keep those classes in a separate branch for now, and ones we've created issues for those classes in an hour or two, create branches that reference those issues.

Will do! I kept them simple, as in the example that you have shown.

**Comment by rcw5890** [comment]
Check #7, #8, #9 for some of these issues
