### ISSUE TITLE
Write text for app & include it in app

### ISSUE THREAD

**Issue by ao20** [SABS-R3-Epidemiology/branchpro#68]
- [x] Write a paragraph of text for the app's landing page.
- [x] Write more detailed introductory descriptions on modelling, branching processes, the branchpro forward model, and inference of R_t. Some equations.
- [x] Decide on where on the app's web page to place all of the above, e.g. initial paragraph at the top, above the figure and sliders, and the detailed descriptions in dropdowns underneath the figure and sliders.
- [x] Add the text to the dash_app.py file (?).
    - [x] dcc.Markdown: https://dash.plotly.com/dash-core-components/markdown
    - [x] Mathjax for LaTeX equations? https://chrisvoncsefalvay.com/2020/07/25/dash-latex/

**Comment by ao20** [comment]
Andrew is writing the text.

**Comment by rcw5890** [comment]
If you'd like some optional sections with more details, that can be done using bootstrap. 

This could be used to hide the "scary" sections but still have them available to more expert users.

https://dash-bootstrap-components.opensource.faculty.ai/docs/components/collapse/
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/fade/

**Comment by rcw5890** [comment]
Hi @ao20 , if you get a chance you may find it useful to take a look at the branch issue-68-text. 

We can place your texts in the files dash_app_text.md and dash_app_collapsible_text.md

**Comment by I-Bouros** [comment]
Recast in issue #78
