### ISSUE TITLE
Get deployment working again

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#73]
Is Heroku working now, or was our problem something permanent?

**Comment by rcw5890** [comment]
Out of interest, I tried a deployment of our code on Google Cloud Platform:

https://branchpro-gcp-test2.nw.r.appspot.com

Google gives you $300 of credit to start, but that money expires after 90 days. I believe we could also apply for their education credits, which would provide $100 per TA and $50 per student expiring after 12 months.

**Comment by I-Bouros** [comment]
I tried over the holiday to make both deployments work with Heroku; no positive outcome. Right now no deployment of the branch-to left in place (though I can reestablish the one we had once the text is in place?).

**Comment by I-Bouros** [comment]
> Out of interest, I tried a deployment of our code on Google Cloud Platform:
> 
> https://branchpro-gcp-test2.nw.r.appspot.com
> 
> Google gives you $300 of credit to start, but that money expires after 90 days. I believe we could also apply for their education credits, which would provide $100 per TA and $50 per student expiring after 12 months.

Should we try this instead, then?
