### ISSUE TITLE
ForwardModel extension for imported cases

### ISSUE THREAD

**Issue by DavAug** [SABS-R3-Epidemiology/branchpro#74]
Implement a LocalBranchProModel class (feel free to come up with a better name) which is able to simulate the incidence number for a given R profile, a given imported cases time series, and a relative reproduction coefficient epsilon.

- [x] Inherit from BranchProModel.
- [x] Add method `set_imported_cases` which has two array-like inputs `times` and `cases` which have to be of the same length. (Those will be used in the simulate method)
- [x] Add epsilon to the model parameters.
- [x] Adjust simulate to incorporate imported cases.
- [x] Generate an example notebook where different scenarios of imported cases and epsilons are illustrated.

**Comment by rcw5890** [comment]
#80
