### ISSUE TITLE
Implement branching process model class

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#8]
Implement branching process model class specified in [here](https://benlambertdotcom.files.wordpress.com/2020/10/branching-process-models-handout.pdf).

- [x] Define the branching process model class in the `models.py` called `BranchProModel` that inherits from #7 .
- [x] Implement the simulate method for the branching process model with inputs and outputs according to the base class doc string. Note that simulate should return the output of one possible run of the stochastic process.
- [x] Write a doc string which explains and defines the model, as an example see [here](https://github.com/pints-team/pints/blob/master/pints/toy/_fitzhugh_nagumo_model.py) for the raw doc string, and [here](https://pints.readthedocs.io/en/stable/toy/fitzhugh_nagumo_model.html) for the sphinx illustration.

**Comment by DavAug** [comment]
Input arguments for class could be `initial_r, serial_intervals`.

In a separate issue we will address how the reproduction profile might be adapted.
