### ISSUE TITLE
Bug in inference - normalisation of serial interval

### ISSUE THREAD

**Issue by rcw5890** [SABS-R3-Epidemiology/branchpro#84]
The BranchProPosterior class happily accepts an unnormalised serial interval, but it never accounts for normalisation in the calculations for the posterior. This causes incorrect inference results whenever an unnormalised serial interval is used.

**Comment by I-Bouros** [comment]
Do you reckon it would also be a good idea to add a method in the inference class to be able to change a serial interval in the inference object? @rcw5890

**Comment by rcw5890** [comment]
> Do you reckon it would also be a good idea to add a method in the inference class to be able to change a serial interval in the inference object? @rcw5890

Yes, I think so. It would be a useful feature if we ever decide to investigate the effects of the serial interval more closely than we have done so far. Feel free to add it to PR #85 , or make a separate issue and do it later.
